## feature scaling (feature transform)
# standardization

In [1]:
conda update matplotlib

Jupyter detected...
3 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Admin\anaconda3

  added / updated specs:
    - matplotlib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2026.8.13  |       haa95532_0         107 KB
    certifi-2026.7.22          |  py313haa95532_0         135 KB
    cycler-0.12.1              |  py313haa95532_0          20 KB
    fonttools-4.63.0           |  py313h1c6eee0_0         5.2 MB
    freetype-2.14.1            |       hfbffc0b_0         514 KB
    kiwisolver-1.5.0           |  py313hd7fb8db_0          83 KB
    libpng-1.6.56              |       h2854ad3_0         239 KB
    matplotlib-3.11.0          |  py313haa95532_0           7 KB
    matplotlib-base-3.11.0     |  py313h330ff07_0         8.2 MB
    openssl-3.5.8              |       hbb43b14_0         8.9 MB
    packaging-26.3             |  py313haa95532_0         380 KB
    pyparsing-3.3.2            |  py313haa95532_0         5.9 MB
    ------------------------------------------------------------
                                           Total:        29.7 MB

The following NEW packages will be INSTALLED:

  cycler             pkgs/main/win-64::cycler-0.12.1-py313haa95532_0
  fonttools          pkgs/main/win-64::fonttools-4.63.0-py313h1c6eee0_0
  kiwisolver         pkgs/main/win-64::kiwisolver-1.5.0-py313hd7fb8db_0
  matplotlib-base    pkgs/main/win-64::matplotlib-base-3.11.0-py313h330ff07_0
  packaging          pkgs/main/win-64::packaging-26.3-py313haa95532_0
  pillow             pkgs/main/win-64::pillow-12.0.0-py313h4212202_1
  pyparsing          pkgs/main/win-64::pyparsing-3.3.2-py313haa95532_0

The following packages will be UPDATED:

  ca-certificates                      2025.11.4-haa95532_0 --> 2026.8.13-haa95532_0
  certifi                        2025.11.12-py313haa95532_0 --> 2026.7.22-py313haa95532_0
  conda                             25.11.1-py313haa95532_0 --> 26.1.1-py313haa95532_0
  freetype                                2.13.3-h0620614_0 --> 2.14.1-hfbffc0b_0
  libpng                                  1.6.50-h46444df_0 --> 1.6.56-h2854ad3_0
  matplotlib                         3.10.6-py313haa95532_1 --> 3.11.0-py313haa95532_0
  openssl                                 3.0.18-h543e019_0 --> 3.5.8-hbb43b14_0



Downloading and Extracting Packages: ...working...
openssl-3.5.8        | 8.9 MB    |            |   0%

matplotlib-base-3.11 | 8.2 MB    |            |   0%


pyparsing-3.3.2      | 5.9 MB    |            |   0%



fonttools-4.63.0     | 5.2 MB    |            |   0%




freetype-2.14.1      | 514 KB    |            |   0%





packaging-26.3       | 380 KB    |            |   0%






libpng-1.6.56        | 239 KB    |            |   0%







certifi-2026.7.22    | 135 KB    |            |   0%








ca-certificates-2026 | 107 KB    |            |   0%









kiwisolver-1.5.0     | 83 KB     |            |   0%










cycler-0.12.1        | 20 KB     |            |   0%











matplotlib-3.11.0    | 7 KB      |            |   0%



fonttools-4.63.0     | 5.2 MB    |            |   0%


pyparsing-3.3.2      | 5.9 MB    |            |   0%

matplotlib-base-3.11 | 8.2 MB    |            |   0%



fonttools-4.63.0     | 5.2 MB    | 5          |   5%


pyparsing-3.3.2      | 5.9 MB    | 2          |   3%
openssl-3.5.8        | 8.9 MB    |            |   0%




freetype-2.14.1      | 514 KB    | 3          |   3%

matplotlib-base-3.11 | 8.2 MB    | 1          |   1%



fonttools-4.63.0     | 5.2 MB    | 8          |   9%


pyparsing-3.3.2      | 5.9 MB    | 4          |   5%




freetype-2.14.1      | 514 KB    | 6          |   6%



fonttools-4.63.0     | 5.2 MB    | #1         |  11%

matplotlib-base-3.11 | 8.2 MB    | 1          |   2%



fonttools-4.63.0     | 5.2 MB    | #6         |  16%


pyparsing-3.3.2      | 5.9 MB    | 6          |   7%




freetype-2.14.1      | 514 KB    | #8         |  19%
openssl-3.5.8        | 8.9 MB    | 1          |   1%


pyparsing-3.3.2      | 5.9 MB    | 9          |   9%




freetype-2.14.1      | 514 KB    | ####9      |  50%

matplotlib-base-3.11 | 8.2 MB    | 3          |   3%



fonttools-4.63.0     | 5.2 MB    | ##1        |  22%


pyparsing-3.3.2      | 5.9 MB    | #1         |  12%




freetype-2.14.1      | 514 KB    | ######2    |  62%

matplotlib-base-3.11 | 8.2 MB    | 4          |   4%



fonttools-4.63.0     | 5.2 MB    | ##8        |  29%

matplotlib-base-3.11 | 8.2 MB    | 5          |   5%




freetype-2.14.1      | 514 KB    | #######4   |  75%




freetype-2.14.1      | 514 KB    | ########## | 100%


pyparsing-3.3.2      | 5.9 MB    | #3         |  14%



fonttools-4.63.0     | 5.2 MB    | ###2       |  33%

matplotlib-base-3.11 | 8.2 MB    | 7          |   7%





packaging-26.3       | 380 KB    | 4          |   4%


pyparsing-3.3.2      | 5.9 MB    | #6         |  16%



fonttools-4.63.0     | 5.2 MB    | ###6       |  36%





packaging-26.3       | 380 KB    | #6         |  17%

matplotlib-base-3.11 | 8.2 MB    | 8          |   8%





packaging-26.3       | 380 KB    | ##9        |  29%



fonttools-4.63.0     | 5.2 MB    | ###9       |  40%


pyparsing-3.3.2      | 5.9 MB    | #8         |  18%





packaging-26.3       | 380 KB    | ######7    |  67%

matplotlib-base-3.11 | 8.2 MB    | 9          |   9%



fonttools-4.63.0     | 5.2 MB    | ####2      |  43%


pyparsing-3.3.2      | 5.9 MB    | #9         |  20%



fonttools-4.63.0     | 5.2 MB    | ####6      |  47%

matplotlib-base-3.11 | 8.2 MB    | #          |  10%


pyparsing-3.3.2      | 5.9 MB    | ##2        |  22%




freetype-2.14.1      | 514 KB    | ########## | 100%




freetype-2.14.1      | 514 KB    | ########## | 100%



fonttools-4.63.0     | 5.2 MB    | #####      |  50%

matplotlib-base-3.11 | 8.2 MB    | #1         |  11%


pyparsing-3.3.2      | 5.9 MB    | ##4        |  24%





packaging-26.3       | 380 KB    | ########8  |  88%





packaging-26.3       | 380 KB    | ########## | 100%



fonttools-4.63.0     | 5.2 MB    | #####4     |  54%

matplotlib-base-3.11 | 8.2 MB    | #2         |  13%


pyparsing-3.3.2      | 5.9 MB    | ##5        |  26%






libpng-1.6.56        | 239 KB    | 6          |   7%



fonttools-4.63.0     | 5.2 MB    | #####7     |  58%

matplotlib-base-3.11 | 8.2 MB    | #3         |  14%


pyparsing-3.3.2      | 5.9 MB    | ##7        |  28%






libpng-1.6.56        | 239 KB    | #####3     |  53%



fonttools-4.63.0     | 5.2 MB    | ######     |  61%

matplotlib-base-3.11 | 8.2 MB    | #4         |  15%


pyparsing-3.3.2      | 5.9 MB    | ##9        |  29%






libpng-1.6.56        | 239 KB    | ########## | 100%






libpng-1.6.56        | 239 KB    | ########## | 100%



fonttools-4.63.0     | 5.2 MB    | ######4    |  64%

matplotlib-base-3.11 | 8.2 MB    | #5         |  15%







certifi-2026.7.22    | 135 KB    | #1         |  12%


pyparsing-3.3.2      | 5.9 MB    | ###        |  31%



fonttools-4.63.0     | 5.2 MB    | ######8    |  68%







certifi-2026.7.22    | 135 KB    | ########2  |  83%


pyparsing-3.3.2      | 5.9 MB    | ###2       |  33%

matplotlib-base-3.11 | 8.2 MB    | #6         |  16%







certifi-2026.7.22    | 135 KB    | ########## | 100%



fonttools-4.63.0     | 5.2 MB    | #######1   |  71%








ca-certificates-2026 | 107 KB    | #4         |  15%


pyparsing-3.3.2      | 5.9 MB    | ###4       |  34%



fonttools-4.63.0     | 5.2 MB    | #######4   |  75%

matplotlib-base-3.11 | 8.2 MB    | #7         |  18%






libpng-1.6.56        | 239 KB    | ########## | 100%








ca-certificates-2026 | 107 KB    | ########9  |  90%








ca-certificates-2026 | 107 KB    | ########## | 100%


pyparsing-3.3.2      | 5.9 MB    | ###6       |  36%



fonttools-4.63.0     | 5.2 MB    | #######7   |  78%







certifi-2026.7.22    | 135 KB    | ########## | 100%

matplotlib-base-3.11 | 8.2 MB    | #8         |  19%





packaging-26.3       | 380 KB    | ########## | 100%
openssl-3.5.8        | 8.9 MB    | 2          |   2%








ca-certificates-2026 | 107 KB    | ########## | 100%









kiwisolver-1.5.0     | 83 KB     | #9         |  19%


pyparsing-3.3.2      | 5.9 MB    | ###8       |  38%









kiwisolver-1.5.0     | 83 KB     | ########## | 100%



fonttools-4.63.0     | 5.2 MB    | ########1  |  81%

matplotlib-base-3.11 | 8.2 MB    | #9         |  20%










cycler-0.12.1        | 20 KB     | ########1  |  82%
openssl-3.5.8        | 8.9 MB    | 2          |   3%










cycler-0.12.1        | 20 KB     | ########## | 100%


pyparsing-3.3.2      | 5.9 MB    | ###9       |  40%



fonttools-4.63.0     | 5.2 MB    | ########4  |  84%

matplotlib-base-3.11 | 8.2 MB    | ##         |  21%
openssl-3.5.8        | 8.9 MB    | 3          |   4%


pyparsing-3.3.2      | 5.9 MB    | ####1      |  42%

matplotlib-base-3.11 | 8.2 MB    | ##1        |  22%



fonttools-4.63.0     | 5.2 MB    | ########7  |  88%


pyparsing-3.3.2      | 5.9 MB    | ####3      |  44%
openssl-3.5.8        | 8.9 MB    | 3          |   4%









kiwisolver-1.5.0     | 83 KB     | ########## | 100%









kiwisolver-1.5.0     | 83 KB     | ########## | 100%

matplotlib-base-3.11 | 8.2 MB    | ##2        |  23%










cycler-0.12.1        | 20 KB     | ########## | 100%










cycler-0.12.1        | 20 KB     | ########## | 100%



fonttools-4.63.0     | 5.2 MB    | #########1 |  91%











matplotlib-3.11.0    | 7 KB      | ########## | 100%











matplotlib-3.11.0    | 7 KB      | ########## | 100%


pyparsing-3.3.2      | 5.9 MB    | ####5      |  46%
openssl-3.5.8        | 8.9 MB    | 4          |   5%

matplotlib-base-3.11 | 8.2 MB    | ##4        |  24%



fonttools-4.63.0     | 5.2 MB    | #########4 |  95%











matplotlib-3.11.0    | 7 KB      | ########## | 100%


pyparsing-3.3.2      | 5.9 MB    | ####8      |  48%

matplotlib-base-3.11 | 8.2 MB    | ##5        |  25%
openssl-3.5.8        | 8.9 MB    | 5          |   6%



fonttools-4.63.0     | 5.2 MB    | #########8 |  98%


pyparsing-3.3.2      | 5.9 MB    | #####      |  50%

matplotlib-base-3.11 | 8.2 MB    | ##6        |  27%
openssl-3.5.8        | 8.9 MB    | 6          |   6%



fonttools-4.63.0     | 5.2 MB    | ########## | 100%


pyparsing-3.3.2      | 5.9 MB    | #####1     |  52%

matplotlib-base-3.11 | 8.2 MB    | ##8        |  28%
openssl-3.5.8        | 8.9 MB    | 7          |   7%


pyparsing-3.3.2      | 5.9 MB    | #####3     |  54%

matplotlib-base-3.11 | 8.2 MB    | ##9        |  30%
openssl-3.5.8        | 8.9 MB    | 8          |   8%

matplotlib-base-3.11 | 8.2 MB    | ###1       |  31%


pyparsing-3.3.2      | 5.9 MB    | #####5     |  56%
openssl-3.5.8        | 8.9 MB    | 9          |  10%

matplotlib-base-3.11 | 8.2 MB    | ###2       |  33%


pyparsing-3.3.2      | 5.9 MB    | #####7     |  57%
openssl-3.5.8        | 8.9 MB    | #          |  11%

matplotlib-base-3.11 | 8.2 MB    | ###4       |  34%
openssl-3.5.8        | 8.9 MB    | #2         |  12%


pyparsing-3.3.2      | 5.9 MB    | #####9     |  59%

matplotlib-base-3.11 | 8.2 MB    | ###6       |  36%
openssl-3.5.8        | 8.9 MB    | #3         |  14%


pyparsing-3.3.2      | 5.9 MB    | ######1    |  61%

matplotlib-base-3.11 | 8.2 MB    | ###8       |  39%
openssl-3.5.8        | 8.9 MB    | #4         |  15%


pyparsing-3.3.2      | 5.9 MB    | ######2    |  63%

matplotlib-base-3.11 | 8.2 MB    | ####       |  40%


pyparsing-3.3.2      | 5.9 MB    | ######4    |  64%
openssl-3.5.8        | 8.9 MB    | #5         |  16%


pyparsing-3.3.2      | 5.9 MB    | ######5    |  66%

matplotlib-base-3.11 | 8.2 MB    | ####1      |  42%
openssl-3.5.8        | 8.9 MB    | #6         |  17%


pyparsing-3.3.2      | 5.9 MB    | ######7    |  67%

matplotlib-base-3.11 | 8.2 MB    | ####3      |  43%
openssl-3.5.8        | 8.9 MB    | #7         |  18%


pyparsing-3.3.2      | 5.9 MB    | ######8    |  68%

matplotlib-base-3.11 | 8.2 MB    | ####4      |  44%
openssl-3.5.8        | 8.9 MB    | #8         |  19%


pyparsing-3.3.2      | 5.9 MB    | ######9    |  70%

matplotlib-base-3.11 | 8.2 MB    | ####5      |  45%


pyparsing-3.3.2      | 5.9 MB    | #######    |  71%
openssl-3.5.8        | 8.9 MB    | #9         |  19%

matplotlib-base-3.11 | 8.2 MB    | ####6      |  47%


pyparsing-3.3.2      | 5.9 MB    | #######2   |  72%

matplotlib-base-3.11 | 8.2 MB    | ####8      |  48%
openssl-3.5.8        | 8.9 MB    | #9         |  20%


pyparsing-3.3.2      | 5.9 MB    | #######3   |  73%

matplotlib-base-3.11 | 8.2 MB    | ####9      |  49%
openssl-3.5.8        | 8.9 MB    | ##         |  21%


pyparsing-3.3.2      | 5.9 MB    | #######4   |  74%

matplotlib-base-3.11 | 8.2 MB    | #####      |  50%
openssl-3.5.8        | 8.9 MB    | ##1        |  21%


pyparsing-3.3.2      | 5.9 MB    | #######5   |  75%

matplotlib-base-3.11 | 8.2 MB    | #####1     |  52%
openssl-3.5.8        | 8.9 MB    | ##2        |  22%


pyparsing-3.3.2      | 5.9 MB    | #######6   |  76%

matplotlib-base-3.11 | 8.2 MB    | #####2     |  53%
openssl-3.5.8        | 8.9 MB    | ##2        |  23%


pyparsing-3.3.2      | 5.9 MB    | #######7   |  77%

matplotlib-base-3.11 | 8.2 MB    | #####4     |  54%


pyparsing-3.3.2      | 5.9 MB    | #######8   |  78%
openssl-3.5.8        | 8.9 MB    | ##3        |  24%

matplotlib-base-3.11 | 8.2 MB    | #####5     |  56%


pyparsing-3.3.2      | 5.9 MB    | #######9   |  79%

matplotlib-base-3.11 | 8.2 MB    | #####7     |  57%
openssl-3.5.8        | 8.9 MB    | ##4        |  24%


pyparsing-3.3.2      | 5.9 MB    | ########   |  81%

matplotlib-base-3.11 | 8.2 MB    | #####9     |  59%
openssl-3.5.8        | 8.9 MB    | ##4        |  25%


pyparsing-3.3.2      | 5.9 MB    | ########1  |  82%

matplotlib-base-3.11 | 8.2 MB    | ######1    |  61%
openssl-3.5.8        | 8.9 MB    | ##5        |  26%


pyparsing-3.3.2      | 5.9 MB    | ########2  |  83%

matplotlib-base-3.11 | 8.2 MB    | ######3    |  64%
openssl-3.5.8        | 8.9 MB    | ##6        |  26%

matplotlib-base-3.11 | 8.2 MB    | ######6    |  66%


pyparsing-3.3.2      | 5.9 MB    | ########4  |  84%
openssl-3.5.8        | 8.9 MB    | ##7        |  27%

matplotlib-base-3.11 | 8.2 MB    | ######8    |  69%


pyparsing-3.3.2      | 5.9 MB    | ########6  |  86%
openssl-3.5.8        | 8.9 MB    | ##8        |  28%

matplotlib-base-3.11 | 8.2 MB    | #######1   |  72%


pyparsing-3.3.2      | 5.9 MB    | ########7  |  88%
openssl-3.5.8        | 8.9 MB    | ##8        |  29%

matplotlib-base-3.11 | 8.2 MB    | #######4   |  74%


pyparsing-3.3.2      | 5.9 MB    | ########9  |  90%
openssl-3.5.8        | 8.9 MB    | ##9        |  30%

matplotlib-base-3.11 | 8.2 MB    | #######7   |  77%


pyparsing-3.3.2      | 5.9 MB    | #########1 |  92%
openssl-3.5.8        | 8.9 MB    | ###1       |  31%

matplotlib-base-3.11 | 8.2 MB    | ########   |  81%


pyparsing-3.3.2      | 5.9 MB    | #########3 |  93%
openssl-3.5.8        | 8.9 MB    | ###1       |  32%


pyparsing-3.3.2      | 5.9 MB    | #########4 |  95%
openssl-3.5.8        | 8.9 MB    | ###2       |  33%

matplotlib-base-3.11 | 8.2 MB    | ########3  |  83%
openssl-3.5.8        | 8.9 MB    | ###4       |  34%

matplotlib-base-3.11 | 8.2 MB    | ########6  |  86%


pyparsing-3.3.2      | 5.9 MB    | #########6 |  96%
openssl-3.5.8        | 8.9 MB    | ###5       |  35%

matplotlib-base-3.11 | 8.2 MB    | ########8  |  88%


pyparsing-3.3.2      | 5.9 MB    | #########8 |  99%
openssl-3.5.8        | 8.9 MB    | ###6       |  36%

matplotlib-base-3.11 | 8.2 MB    | #########  |  91%


pyparsing-3.3.2      | 5.9 MB    | ########## | 100%
openssl-3.5.8        | 8.9 MB    | ###7       |  37%

matplotlib-base-3.11 | 8.2 MB    | #########3 |  93%

matplotlib-base-3.11 | 8.2 MB    | #########5 |  95%
openssl-3.5.8        | 8.9 MB    | ###8       |  38%

matplotlib-base-3.11 | 8.2 MB    | #########7 |  97%
openssl-3.5.8        | 8.9 MB    | ###9       |  40%

matplotlib-base-3.11 | 8.2 MB    | #########9 |  99%
openssl-3.5.8        | 8.9 MB    | ####       |  41%
openssl-3.5.8        | 8.9 MB    | ####1      |  42%
openssl-3.5.8        | 8.9 MB    | ####2      |  43%

matplotlib-base-3.11 | 8.2 MB    | ########## | 100%
openssl-3.5.8        | 8.9 MB    | ####3      |  44%
openssl-3.5.8        | 8.9 MB    | ####4      |  45%
openssl-3.5.8        | 8.9 MB    | ####5      |  46%
openssl-3.5.8        | 8.9 MB    | ####7      |  47%
openssl-3.5.8        | 8.9 MB    | ####8      |  48%
openssl-3.5.8        | 8.9 MB    | ####9      |  50%
openssl-3.5.8        | 8.9 MB    | #####1     |  52%
openssl-3.5.8        | 8.9 MB    | #####4     |  54%
openssl-3.5.8        | 8.9 MB    | #####7     |  57%
openssl-3.5.8        | 8.9 MB    | ######     |  60%
openssl-3.5.8        | 8.9 MB    | ######3    |  63%
openssl-3.5.8        | 8.9 MB    | ######6    |  66%
openssl-3.5.8        | 8.9 MB    | #######    |  70%
openssl-3.5.8        | 8.9 MB    | #######4   |  74%
openssl-3.5.8        | 8.9 MB    | #######8   |  78%


pyparsing-3.3.2      | 5.9 MB    | ########## | 100%
openssl-3.5.8        | 8.9 MB    | ########2  |  83%
openssl-3.5.8        | 8.9 MB    | ########7  |  88%
openssl-3.5.8        | 8.9 MB    | #########2 |  93%
openssl-3.5.8        | 8.9 MB    | #########7 |  98%
openssl-3.5.8        | 8.9 MB    | ########## | 100%
openssl-3.5.8        | 8.9 MB    | ########## | 100%

matplotlib-base-3.11 | 8.2 MB    | ########## | 100%



fonttools-4.63.0     | 5.2 MB    | ########## | 100%














































































                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Channel "defaults" has the following notices:
  [info] -- Thu Aug  6 00:00:00 2026
  main-x (Anaconda's new authenticated channel) is now generally available, with thousands of additional packages from our secure supply chain. Get started at: https://anaconda.com/docs/getting-started/main-x?utm_source=channel_notices


Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd # data processing 
import numpy as np   # linear algebra
import matplotlib.pyplot as plt 
import seaborn as sns

In [17]:
df = pd.read_csv('Social_Network_Ads.csv')

In [18]:
df.sample(5)

     Age  EstimatedSalary  Purchased
311   39            96000          1
213   35            58000          0
393   60            42000          1
163   35            38000          0
35    35            27000          0

## train_test_split

In [24]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    df.drop("Purchased", axis=1), df["Purchased"], test_size=0.3
)

x_train.shape,x_test.shape

((280, 2), (120, 2))

## StandardScaler

In [32]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [30]:
scaler.mean_

array([3.80428571e+01, 7.13285714e+04])

In [41]:
x_train_scaled = pd.DataFrame(scaler.transform(x_train), columns=x_train.columns)
x_test_scaled = pd.DataFrame(scaler.transform(x_test), columns=x_test.columns)

x_train_scaled.sample(3)

          Age  EstimatedSalary
163  1.580195        -0.922413
142 -0.190369        -0.608556
232 -1.401807        -0.152037

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
lr = LogisticRegression()
lr_scaled = LogisticRegression()

In [46]:
lr.fit(X_train,y_train)
lr_scaled.fit(x_train_scaled,y_train)

LogisticRegression()

In [48]:
y_pred = lr.predict(x_test)
y_pred_scaler = lr_scaled.predict(x_test_scaled)

In [49]:
from sklearn.metrics import accuracy_score

In [53]:
print("actual",accuracy_score (y_test,y_pred))
print("scaled",accuracy_score (y_test,y_pred_scaler))

actual 0.7416666666666667
scaled 0.875

In [54]:
print("actual", accuracy_score(y_test, y_pred) * 100)
print("scaled", accuracy_score(y_test, y_pred_scaler) * 100)

actual 74.16666666666667
scaled 87.5