In [13]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df = pd.read_csv('wine_data.csv',header=None,usecols=[0,1,2])
df.columns=['class_label','alcohol','malic_acid']

In [15]:
df.sample(3)

    class_label  alcohol  malic_acid
50            1    13.05        1.73
23            1    12.85        1.60
4             1    13.24        2.59

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.drop("class_label", axis=1),
    df["class_label"],
    test_size=0.3,
    random_state=0,
)

X_train.shape

(124, 2)

In [18]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [22]:
np.round(X_train_scaled.describe(), 1)

       alcohol  malic_acid
count    124.0       124.0
mean       0.5         0.3
std        0.2         0.2
min        0.0         0.0
25%        0.4         0.2
50%        0.5         0.2
75%        0.7         0.5
max        1.0         1.0

In [23]:
np.round(X_train.describe(), 1)

       alcohol  malic_acid
count    124.0       124.0
mean      13.0         2.4
std        0.8         1.1
min       11.0         0.9
25%       12.4         1.6
50%       13.0         1.9
75%       13.6         3.2
max       14.8         5.6

In [24]:
# View 5 random rows from the scaled dataset
X_train_scaled.sample(5)

     alcohol  malic_acid
92  0.381720    0.449580
15  0.360215    0.010504
65  0.830645    0.123950
38  0.440860    0.018908
39  1.000000    0.176471

In [25]:
X_train.sample(5)

     alcohol  malic_acid
108    12.22        1.29
75     11.66        1.88
57     13.29        1.97
150    13.50        3.12
119    12.00        3.43