In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('tested_titanic.csv')
df = df[['Age', 'Fare', 'Survived']]

In [3]:
df.sample(5)

      Age     Fare  Survived
33    NaN  23.4500         1
145  31.0  18.0000         0
76    NaN   8.0500         0
257  28.0   8.0500         0
364  25.0  55.4417         1

In [5]:
df.isnull().mean()*100

Age         20.574163
Fare         0.239234
Survived     0.000000
dtype: float64

In [6]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2
)

In [8]:
# Create an imputed column with original values
X_train['Age_imputed'] = X_train['Age']
X_test['Age_imputed'] = X_test['Age']

In [9]:
# Extract random samples from non-null values to fill missing values
num_missing_train = X_train['Age_imputed'].isnull().sum()
random_sample_train = (
    X_train['Age'].dropna().sample(num_missing_train, random_state=0)
)
random_sample_train.index = X_train[X_train['Age_imputed'].isnull()].index
X_train.loc[X_train['Age_imputed'].isnull(), 'Age_imputed'] = (
    random_sample_train
)

num_missing_test = X_test['Age_imputed'].isnull().sum()
random_sample_test = (
    X_train['Age']
    .dropna()
    .sample(num_missing_test, random_state=0)
)  # Note: sample from train set
random_sample_test.index = X_test[X_test['Age_imputed'].isnull()].index
X_test.loc[X_test['Age_imputed'].isnull(), 'Age_imputed'] = random_sample_test

In [13]:
X_train.sample(5)

      Age     Fare  Age_imputed
44   45.0  52.5542         45.0
54    NaN  15.5792         22.0
48   60.0  76.2917         60.0
187  17.0   8.0500         17.0
340  18.0  10.5000         18.0

In [15]:
data = pd.read_csv('train.csv', usecols=['GarageQual', 'FireplaceQu', 'SalePrice'])

In [16]:
data.head()

  FireplaceQu GarageQual  SalePrice
0         NaN         TA     208500
1          TA         TA     181500
2          TA         TA     223500
3          Gd         TA     140000
4          TA         TA     250000

In [17]:
data.isnull().mean() * 100

FireplaceQu    47.260274
GarageQual      5.547945
SalePrice       0.000000
dtype: float64

In [18]:
X = data
y = data['SalePrice']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2
)

In [20]:
X_train['GarageQual_imputed'] = X_train['GarageQual']
X_test['GarageQual_imputed'] = X_test['GarageQual']

X_train['FireplaceQu_imputed'] = X_train['FireplaceQu']
X_test['FireplaceQu_imputed'] = X_test['FireplaceQu']

In [21]:
X_train.sample(5)

     FireplaceQu GarageQual  SalePrice GarageQual_imputed FireplaceQu_imputed
135           Gd         TA     174000                 TA                  Gd
461          NaN         TA     155000                 TA                 NaN
1314          TA         TA     119000                 TA                  TA
1070         NaN         TA     135000                 TA                 NaN
636           Po        NaN      60000                NaN                  Po

In [22]:
X_train['GarageQual_imputed'][
    X_train['GarageQual_imputed'].isnull()
] = X_train['GarageQual'].dropna().sample(
    X_train['GarageQual'].isnull().sum()
).values
X_test['GarageQual_imputed'][
    X_test['GarageQual_imputed'].isnull()
] = X_train['GarageQual'].dropna().sample(
    X_test['GarageQual'].isnull().sum()
).values

X_train['FireplaceQu_imputed'][
    X_train['FireplaceQu_imputed'].isnull()
] = X_train['FireplaceQu'].dropna().sample(
    X_train['FireplaceQu'].isnull().sum()
).values
X_test['FireplaceQu_imputed'][
    X_test['FireplaceQu_imputed'].isnull()
] = X_train['FireplaceQu'].dropna().sample(
    X_test['FireplaceQu'].isnull().sum()
).values

C:\Users\Admin\AppData\Local\Temp\ipykernel_3472\2972811377.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_train['GarageQual_imputed'][
C:\Users\Admin\AppData\Local\Temp\ipykernel_3472\2972811377.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['GarageQual_imputed'][
C:\Users\Admin\AppData\Local\Temp\ipykernel_3472\2972811377.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_test['GarageQual_imputed'][
C:\Users\Admin\AppData\Local\Temp\ipykernel_3472\2972811377.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['GarageQual_imputed'][
C:\Users\Admin\AppData\Local\Temp\ipykernel_3472\2972811377.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_train['FireplaceQu_imputed'][
C:\Users\Admin\AppData\Local\Temp\ipykernel_3472\2972811377.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['FireplaceQu_imputed'][
C:\Users\Admin\AppData\Local\Temp\ipykernel_3472\2972811377.py:17: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_test['FireplaceQu_imputed'][
C:\Users\Admin\AppData\Local\Temp\ipykernel_3472\2972811377.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['FireplaceQu_imputed'][

In [23]:
# GarageQual_imputed ke liye (Train set)
train_missing_mask = X_train['GarageQual_imputed'].isnull()
train_samples = (
    X_train['GarageQual']
    .dropna()
    .sample(train_missing_mask.sum(), random_state=0)
)
X_train.loc[train_missing_mask, 'GarageQual_imputed'] = train_samples.values

# GarageQual_imputed ke liye (Test set)
test_missing_mask = X_test['GarageQual_imputed'].isnull()
test_samples = (
    X_train['GarageQual']
    .dropna()
    .sample(test_missing_mask.sum(), random_state=0)
)
X_test.loc[test_missing_mask, 'GarageQual_imputed'] = test_samples.values

# FireplaceQu_imputed ke liye (Train set)
train_fire_mask = X_train['FireplaceQu_imputed'].isnull()
train_fire_samples = (
    X_train['FireplaceQu'].dropna().sample(train_fire_mask.sum(), random_state=0)
)
X_train.loc[train_fire_mask, 'FireplaceQu_imputed'] = train_fire_samples.values

# FireplaceQu_imputed ke liye (Test set)
test_fire_mask = X_test['FireplaceQu_imputed'].isnull()
test_fire_samples = (
    X_train['FireplaceQu'].dropna().sample(test_fire_mask.sum(), random_state=0)
)
X_test.loc[test_fire_mask, 'FireplaceQu_imputed'] = test_fire_samples.values