In [1]:
import pandas as pd

In [25]:
df = pd.read_json('train.json')

In [26]:
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

## working with sql

In [27]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 4.8 MB/s eta 0:00:03
     ----- ---------------------------------- 1.6/11.9 MB 5.1 MB/s eta 0:00:02
     ------- -------------------------------- 2.4/11.9 MB 4.2 MB/s eta 0:00:03
     ----------- ---------------------------- 3.4/11.9 MB 4.3 MB/s eta 0:00:02
     ------------- -------------------------- 3.9/11.9 MB 4.1 MB/s eta 0:00:02
     --------------- ------------------------ 4.7/11.9 MB 4.0 MB/s eta 0:00:02
     ------------------- -------------------- 5.8/11.9 MB 4.1 MB/s eta 0:00:02
     ---------------------- ----------------- 6.6/11.9 MB 4.1 MB/s eta 0:00:02
     ----------------------- ---------------- 7.1/11.9 MB 4.0 MB/s eta 0:00:02
     -------------------------- ------------- 7.9/11.9 MB 3.9 MB/s eta 0:00:02
     ----------------------------- ---------- 8.7/11.9 MB 3.9 MB/s eta 0:00:01
     --------------------------------- ------ 10.0/11.9 MB 4.0 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 4.0 MB/s eta 0:00:01
     -------------------------------------- - 11.3/11.9 MB 3.9 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 3.9 MB/s  0:00:03
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248050 sha256=3827305f753a36cfb16c3a9e73379688a166b8cc946c2f634ba8eb1ceacd5fce
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Admin\anaconda3\Lib\site-packages)

In [32]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\admin\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\admin\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [28]:
import mysql.connector

In [30]:
conn = mysql.connector.connect(host = 'localhost',
                              user = 'root',
                              password = '',
                              database = 'world')

In [37]:
df = pd.read_sql_query("SELECT * FROM COUNTRY WHERE LifeExpectancy > 60  ", conn)

C:\Users\Admin\AppData\Local\Temp\ipykernel_25712\959290711.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM COUNTRY WHERE LifeExpectancy > 60  ", conn)

In [39]:
df.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129,AW
1,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62,AI
2,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34,AL
3,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,,55,AD
4,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33,AN

In [41]:
# api calling

In [42]:
import requests