In [2]:
import pandas as pd 
import requests
from bs4 import BeautifulSoup
!pip install jupyterlab-code-formatter black autopep8

Requirement already satisfied: jupyterlab-code-formatter in c:\users\admin\anaconda3\lib\site-packages (3.1.0)
Requirement already satisfied: black in c:\users\admin\anaconda3\lib\site-packages (25.9.0)
Requirement already satisfied: autopep8 in c:\users\admin\anaconda3\lib\site-packages (2.0.4)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\admin\anaconda3\lib\site-packages (from jupyterlab-code-formatter) (2.16.0)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from jupyterlab-code-formatter) (25.0)
Requirement already satisfied: anyio>=3.1.0 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (4.10.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (21.3.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (3.1.6)
Requirement already satisfied: jupyter-client>=7.4.4 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (5.8.1)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.5.3)
Requirement already satisfied: nbconvert>=6.4.4 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (7.16.6)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (5.10.4)
Requirement already satisfied: overrides>=5.0 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.21.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (2.0.15)
Requirement already satisfied: pyzmq>=24 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (27.1.0)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.18.1)
Requirement already satisfied: tornado>=6.2.0 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (6.5.1)
Requirement already satisfied: traitlets>=5.6.0 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (5.14.3)
Requirement already satisfied: websocket-client>=1.7 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (1.8.0)
Requirement already satisfied: click>=8.0.0 in c:\users\admin\anaconda3\lib\site-packages (from black) (8.2.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\admin\anaconda3\lib\site-packages (from black) (1.0.0)
Requirement already satisfied: pathspec>=0.9.0 in c:\users\admin\anaconda3\lib\site-packages (from black) (0.12.1)
Requirement already satisfied: platformdirs>=2 in c:\users\admin\anaconda3\lib\site-packages (from black) (4.5.0)
Requirement already satisfied: pytokens>=0.1.10 in c:\users\admin\anaconda3\lib\site-packages (from black) (0.3.0)
Requirement already satisfied: pycodestyle>=2.10.0 in c:\users\admin\anaconda3\lib\site-packages (from autopep8) (2.12.1)
Requirement already satisfied: idna>=2.8 in c:\users\admin\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (3.11)
Requirement already satisfied: sniffio>=1.1 in c:\users\admin\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\users\admin\anaconda3\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (25.1.0)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from click>=8.0.0->black) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\anaconda3\lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (2.9.0.post0)
Requirement already satisfied: pywin32>=300 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (311)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (4.25.0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (3.2.1)
Requirement already satisfied: pyyaml>=5.3 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (6.0.3)
Requirement already satisfied: referencing in c:\users\admin\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.37.0)
Requirement already satisfied: rfc3339-validator in c:\users\admin\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\admin\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.1.1)
Requirement already satisfied: attrs>=22.2.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (2025.9.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.28.0)
Requirement already satisfied: fqdn in c:\users\admin\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\admin\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (1.1.0)
Requirement already satisfied: uri-template in c:\users\admin\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\admin\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (25.10.0)
Requirement already satisfied: beautifulsoup4 in c:\users\admin\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in c:\users\admin\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (6.3.0)
Requirement already satisfied: defusedxml in c:\users\admin\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\admin\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\admin\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (3.1.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\admin\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\admin\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (1.5.1)
Requirement already satisfied: pygments>=2.4.1 in c:\users\admin\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (2.19.2)
Requirement already satisfied: webencodings in c:\users\admin\anaconda3\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\admin\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\admin\anaconda3\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (2.21.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (1.17.0)
Requirement already satisfied: lark>=1.2.2 in c:\users\admin\anaconda3\lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (1.3.1)
Requirement already satisfied: cffi>=1.0.1 in c:\users\admin\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (2.0.0)
Requirement already satisfied: pycparser in c:\users\admin\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (2.23)
Requirement already satisfied: soupsieve>1.2 in c:\users\admin\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\admin\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (4.15.0)
Requirement already satisfied: arrow>=0.15.0 in c:\users\admin\anaconda3\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (1.4.0)
Requirement already satisfied: tzdata in c:\users\admin\anaconda3\lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab-code-formatter) (2025.2)

In [3]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'
}

webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers=headers).text

In [4]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\admin\anaconda3\lib\site-packages (5.3.0)

In [5]:
soup = BeautifulSoup(webpage, 'lxml')

In [6]:
company = soup.find_all('div', class_='companyCardWrapper')

In [7]:
name = []
rating = []
reviews = []
classification = []
role = []
image = []
quantitative_datapoints = []

for i in company:
    name.append(i.find('h2', class_='companyCardWrapper__companyName').text.strip())
    rating.append(i.find('div', class_='rating_star_container').text.strip())
    role.append(i.find('div', class_='companyCardWrapper__ratingHeader').text.strip())

d = {'name': name, 'rating': rating, 'role': role}
df = pd.DataFrame(d)

In [8]:
df.head()

        name rating                  role
0        TCS    3.2  Critically Rated For
1  Accenture    3.7  Critically Rated For
2      Wipro    3.6  Critically Rated For
3  Cognizant    3.7  Critically Rated For
4  Capgemini    3.6      Highly Rated For

In [9]:
dfs = []

for j in range(1, 20):
    url = 'https://www.ambitionbox.com/list-of-companies?page={}'.format(j)
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage = requests.get(url, headers=headers).text
    soup = BeautifulSoup(webpage, 'lxml')
    company = soup.find_all('div', class_='companyCardWrapper')
    
    name = []
    rating = []
    role = []
    
    for i in company:
        comp_name = i.find('h2', class_='companyCardWrapper__companyName')
        comp_rating = i.find('div', class_='rating_star_container')
        comp_role = i.find('div', class_='companyCardWrapper__ratingHeader')
        
        name.append(comp_name.text.strip() if comp_name else None)
        rating.append(comp_rating.text.strip() if comp_rating else None)
        role.append(comp_role.text.strip() if comp_role else None)
    
    d = {'name': name, 'rating': rating, 'role': role}
    dfs.append(pd.DataFrame(d))

final = pd.concat(dfs, ignore_index=True)

In [10]:
final.head()

        name rating                  role
0        TCS    3.2  Critically Rated For
1  Accenture    3.7  Critically Rated For
2      Wipro    3.6  Critically Rated For
3  Cognizant    3.7  Critically Rated For
4  Capgemini    3.6      Highly Rated For

In [11]:
final.shape

(380, 3)